(* Build omake-boot.exe. Assuming OCaml for Windows installed *)

let ocamlopt = "ocamlopt.opt -w +a-4-32-30-42-40-41 -g -thread"

let cmd s =
  print_endline s; 
  let x = Sys.command s in
  (if x <> 0 then
    exit (-1))

let cmi_of_mli mli = cmd ("ocamlc.opt -w +a-4-32-30-42-40-41 -g -thread -c " ^ mli)

let cmx_of_ml ml = cmd (ocamlopt ^ " -c " ^ ml)

let co_of_c c = cmd ("i686-w64-mingw32-gcc -Ic:/ocaml/lib -Ic:/ocaml/lib/caml -I../src/clib -o " ^ c ^ "o -c " ^ c)

let _ =
  cmd "mkdir boot";
  Sys.chdir "boot";
  cmd "cp ../src/clib/lm_heap.c c_lm_heap.c";
  cmd "cp ../src/clib/lm_channel.c c_lm_channel.c";
  cmd "cp ../src/clib/lm_printf.c c_lm_printf.c";
  cmd "cp ../src/clib/lm_ctype.c c_lm_ctype.c";
  cmd "cp ../src/clib/lm_uname_ext.c c_lm_uname_ext.c";
  cmd "cp ../src/clib/lm_unix_cutil.c c_lm_unix_cutil.c";
  cmd "cp ../src/clib/lm_compat_win32.c c_lm_compat_win32.c";
  cmd "cp ../src/clib/readline.c c_readline.c";
  cmd "cp ../src/clib/omake_shell_sys.c c_omake_shell_sys.c";
  cmd "cp ../src/clib/omake_shell_spawn.c c_omake_shell_spawn.c";
  cmd "cp ../src/clib/fam_win32.c c_fam_win32.c";
  cmd "cp ../src/clib/fam_kqueue.c c_fam_kqueue.c";
  cmd "cp ../src/clib/fam_inotify.c c_fam_inotify.c";
  cmd "cp ../src/clib/lm_notify.c c_lm_notify.c";
  cmd "cp ../src/clib/lm_termsize.c c_lm_termsize.c";
  cmd "cp ../src/clib/lm_terminfo.c c_lm_terminfo.c";
  cmd "cp ../src/clib/lm_fs_case_sensitive.c c_lm_fs_case_sensitive.c";
  cmd "cp ../src/libmojave/lm_arg.ml lm_arg.ml";
  cmd "cp ../src/libmojave/lm_arg.mli lm_arg.mli";
  cmd "cp ../src/libmojave/lm_array_util.ml lm_array_util.ml";
  cmd "cp ../src/libmojave/lm_array_util.mli lm_array_util.mli";
  cmd "cp ../src/libmojave/lm_bitset.ml lm_bitset.ml";
  cmd "cp ../src/libmojave/lm_bitset.mli lm_bitset.mli";
  cmd "cp ../src/libmojave/lm_channel.ml lm_channel.ml";
  cmd "cp ../src/libmojave/lm_channel.mli lm_channel.mli";
  cmd "cp ../src/libmojave/lm_db.ml lm_db.ml";
  cmd "cp ../src/libmojave/lm_db.mli lm_db.mli";
  cmd "cp ../src/libmojave/lm_debug.ml lm_debug.ml";
  cmd "cp ../src/libmojave/lm_debug.mli lm_debug.mli";
  cmd "cp ../src/libmojave/lm_filename_util.ml lm_filename_util.ml";
  cmd "cp ../src/libmojave/lm_filename_util.mli lm_filename_util.mli";
  cmd "cp ../src/libmojave/lm_fs_case_sensitive.ml lm_fs_case_sensitive.ml";
  cmd "cp ../src/libmojave/lm_fs_case_sensitive.mli lm_fs_case_sensitive.mli";
  cmd "cp ../src/libmojave/lm_handle_table.ml lm_handle_table.ml";
  cmd "cp ../src/libmojave/lm_handle_table.mli lm_handle_table.mli";
  cmd "cp ../src/libmojave/lm_hash.ml lm_hash.ml";
  cmd "cp ../src/libmojave/lm_hash.mli lm_hash.mli";
  cmd "cp ../src/libmojave/lm_hash_code.ml lm_hash_code.ml";
  cmd "cp ../src/libmojave/lm_hash_code.mli lm_hash_code.mli";
  cmd "cp ../src/libmojave/lm_heap.ml lm_heap.ml";
  cmd "cp ../src/libmojave/lm_heap.mli lm_heap.mli";
  cmd "cp ../src/libmojave/lm_index.ml lm_index.ml";
  cmd "cp ../src/libmojave/lm_index.mli lm_index.mli";
  cmd "cp ../src/libmojave/lm_instrument.ml lm_instrument.ml";
  cmd "cp ../src/libmojave/lm_instrument.mli lm_instrument.mli";
  cmd "cp ../src/libmojave/lm_int_handle_table.ml lm_int_handle_table.ml";
  cmd "cp ../src/libmojave/lm_int_handle_table.mli lm_int_handle_table.mli";
  cmd "cp ../src/libmojave/lm_int_set.ml lm_int_set.ml";
  cmd "cp ../src/libmojave/lm_int_set.mli lm_int_set.mli";
  cmd "cp ../src/libmojave/lm_list_util.ml lm_list_util.ml";
  cmd "cp ../src/libmojave/lm_list_util.mli lm_list_util.mli";
  cmd "cp ../src/libmojave/lm_location.ml lm_location.ml";
  cmd "cp ../src/libmojave/lm_location.mli lm_location.mli";
  cmd "cp ../src/libmojave/lm_map.ml lm_map.ml";
  cmd "cp ../src/libmojave/lm_map.mli lm_map.mli";
  cmd "cp ../src/libmojave/lm_map_sig.ml lm_map_sig.ml";
  cmd "cp ../src/libmojave/lm_marshal.ml lm_marshal.ml";
  cmd "cp ../src/libmojave/lm_marshal.mli lm_marshal.mli";
  cmd "cp ../src/libmojave/lm_notify.ml lm_notify.ml";
  cmd "cp ../src/libmojave/lm_notify.mli lm_notify.mli";
  cmd "cp ../src/libmojave/lm_position.ml lm_position.ml";
  cmd "cp ../src/libmojave/lm_position.mli lm_position.mli";
  cmd "cp ../src/libmojave/lm_printf.ml lm_printf.ml";
  cmd "cp ../src/libmojave/lm_printf.mli lm_printf.mli";
  cmd "cp ../src/libmojave/lm_readline.ml lm_readline.ml";
  cmd "cp ../src/libmojave/lm_readline.mli lm_readline.mli";
  cmd "cp ../src/libmojave/lm_set.ml lm_set.ml";
  cmd "cp ../src/libmojave/lm_set.mli lm_set.mli";
  cmd "cp ../src/libmojave/lm_set_sig.ml lm_set_sig.ml";
  cmd "cp ../src/libmojave/lm_string_set.ml lm_string_set.ml";
  cmd "cp ../src/libmojave/lm_string_set.mli lm_string_set.mli";
  cmd "cp ../src/libmojave/lm_string_util.ml lm_string_util.ml";
  cmd "cp ../src/libmojave/lm_string_util.mli lm_string_util.mli";
  cmd "cp ../src/libmojave/lm_symbol.ml lm_symbol.ml";
  cmd "cp ../src/libmojave/lm_symbol.mli lm_symbol.mli";
  cmd "cp ../src/libmojave/lm_terminfo.ml lm_terminfo.ml";
  cmd "cp ../src/libmojave/lm_terminfo.mli lm_terminfo.mli";
  cmd "cp ../src/libmojave/lm_termsize.ml lm_termsize.ml";
  cmd "cp ../src/libmojave/lm_termsize.mli lm_termsize.mli";
  cmd "cp ../src/libmojave/lm_thread.ml lm_thread.ml";
  cmd "cp ../src/libmojave/lm_thread.mli lm_thread.mli";
  cmd "cp ../src/libmojave/lm_thread_core.mli lm_thread_core.mli";
  cmd "cp ../src/libmojave/lm_thread_pool.mli lm_thread_pool.mli";
  cmd "cp ../src/libmojave/lm_thread_sig.ml lm_thread_sig.ml";
  cmd "cp ../src/libmojave/lm_uname.ml lm_uname.ml";
  cmd "cp ../src/libmojave/lm_uname.mli lm_uname.mli";
  cmd "cp ../src/libmojave/lm_unix_util.ml lm_unix_util.ml";
  cmd "cp ../src/libmojave/lm_unix_util.mli lm_unix_util.mli";
  cmd "cp ../src/libmojave/lm_wild.ml lm_wild.ml";
  cmd "cp ../src/libmojave/lm_wild.mli lm_wild.mli";
  cmd "cp ../src/libmojave/lm_thread_pool_system.ml lm_thread_pool.ml";
  cmd "cp ../src/libmojave/lm_thread_core_system.ml lm_thread_core.ml";
  cmd "cp ../src/front/lm_glob.ml lm_glob.ml";
  cmd "cp ../src/front/lm_glob.mli lm_glob.mli";
  cmd "cp ../src/front/lm_hash_cons.ml lm_hash_cons.ml";
  cmd "cp ../src/front/lm_hash_cons.mli lm_hash_cons.mli";
  cmd "cp ../src/front/lm_lexer.ml lm_lexer.ml";
  cmd "cp ../src/front/lm_lexer.mli lm_lexer.mli";
  cmd "cp ../src/front/lm_parser.ml lm_parser.ml";
  cmd "cp ../src/front/lm_parser.mli lm_parser.mli";
  cmd "cp ../src/magic/omake_gen_magic.ml omake_gen_magic.ml";
  cmd "cp ../src/ir/omake_cache.ml omake_cache.ml";
  cmd "cp ../src/ir/omake_cache.mli omake_cache.mli";
  cmd "cp ../src/ir/omake_cache_type.ml omake_cache_type.ml";
  cmd "cp ../src/ir/omake_command.ml omake_command.ml";
  cmd "cp ../src/ir/omake_command.mli omake_command.mli";
  cmd "cp ../src/ir/omake_command_type.ml omake_command_type.ml";
  cmd "cp ../src/ir/omake_command_type.mli omake_command_type.mli";
  cmd "cp ../src/ir/omake_install.ml omake_install.ml";
  cmd "cp ../src/ir/omake_install.mli omake_install.mli";
  cmd "cp ../src/ir/omake_ir.ml omake_ir.ml";
  cmd "cp ../src/ir/omake_ir_free_vars.ml omake_ir_free_vars.ml";
  cmd "cp ../src/ir/omake_ir_free_vars.mli omake_ir_free_vars.mli";
  cmd "cp ../src/ir/omake_ir_print.ml omake_ir_print.ml";
  cmd "cp ../src/ir/omake_ir_print.mli omake_ir_print.mli";
  cmd "cp ../src/ir/omake_ir_util.ml omake_ir_util.ml";
  cmd "cp ../src/ir/omake_lexer.ml omake_lexer.ml";
  cmd "cp ../src/ir/omake_node.ml omake_node.ml";
  cmd "cp ../src/ir/omake_node.mli omake_node.mli";
  cmd "cp ../src/ir/omake_node_sig.ml omake_node_sig.ml";
  cmd "cp ../src/ir/omake_node_type.ml omake_node_type.ml";
  cmd "cp ../src/ir/omake_options.ml omake_options.ml";
  cmd "cp ../src/ir/omake_options.mli omake_options.mli";
  cmd "cp ../src/ir/omake_parser.ml omake_parser.ml";
  cmd "cp ../src/ir/omake_pos.ml omake_pos.ml";
  cmd "cp ../src/ir/omake_pos.mli omake_pos.mli";
  cmd "cp ../src/ir/omake_shell_type.ml omake_shell_type.ml";
  cmd "cp ../src/ir/omake_state.ml omake_state.ml";
  cmd "cp ../src/ir/omake_state.mli omake_state.mli";
  cmd "cp ../src/ir/omake_symbol.ml omake_symbol.ml";
  cmd "cp ../src/ir/omake_value_print.ml omake_value_print.ml";
  cmd "cp ../src/ir/omake_value_print.mli omake_value_print.mli";
  cmd "cp ../src/ir/omake_value_type.ml omake_value_type.ml";
  cmd "cp ../src/ir/omake_value_util.ml omake_value_util.ml";
  cmd "cp ../src/ir/omake_value_util.mli omake_value_util.mli";
  cmd "cp ../src/ir/omake_var.ml omake_var.ml";
  cmd "cp ../src/ir/omake_var.mli omake_var.mli";
  cmd "cp ../src/exec/omake_exec.ml omake_exec.ml";
  cmd "cp ../src/exec/omake_exec.mli omake_exec.mli";
  cmd "cp ../src/exec/omake_exec_id.ml omake_exec_id.ml";
  cmd "cp ../src/exec/omake_exec_id.mli omake_exec_id.mli";
  cmd "cp ../src/exec/omake_exec_local.ml omake_exec_local.ml";
  cmd "cp ../src/exec/omake_exec_local.mli omake_exec_local.mli";
  cmd "cp ../src/exec/omake_exec_notify.ml omake_exec_notify.ml";
  cmd "cp ../src/exec/omake_exec_notify.mli omake_exec_notify.mli";
  cmd "cp ../src/exec/omake_exec_print.ml omake_exec_print.ml";
  cmd "cp ../src/exec/omake_exec_print.mli omake_exec_print.mli";
  cmd "cp ../src/exec/omake_exec_remote.ml omake_exec_remote.ml";
  cmd "cp ../src/exec/omake_exec_remote.mli omake_exec_remote.mli";
  cmd "cp ../src/exec/omake_exec_type.ml omake_exec_type.ml";
  cmd "cp ../src/exec/omake_exec_util.ml omake_exec_util.ml";
  cmd "cp ../src/exec/omake_exec_util.mli omake_exec_util.mli";
  cmd "cp ../src/ast/omake_ast.ml omake_ast.ml";
  cmd "cp ../src/ast/omake_ast_print.ml omake_ast_print.ml";
  cmd "cp ../src/ast/omake_ast_print.mli omake_ast_print.mli";
  cmd "cp ../src/ast/omake_ast_util.ml omake_ast_util.ml";
  cmd "cp ../src/ast/omake_ast_util.mli omake_ast_util.mli";
  cmd "cp ../src/env/omake_ast_lex.mli omake_ast_lex.mli";
  cmd "cp ../src/env/omake_command_digest.ml omake_command_digest.ml";
  cmd "cp ../src/env/omake_command_digest.mli omake_command_digest.mli";
  cmd "cp ../src/env/omake_env.ml omake_env.ml";
  cmd "cp ../src/env/omake_env.mli omake_env.mli";
  cmd "cp ../src/env/omake_exn_print.ml omake_exn_print.ml";
  cmd "cp ../src/env/omake_exn_print.mli omake_exn_print.mli";
  cmd "cp ../src/env/omake_exp_lex.ml omake_exp_lex.ml";
  cmd "cp ../src/env/omake_exp_lex.mli omake_exp_lex.mli";
  cmd "cp ../src/env/omake_gen_parse.ml omake_gen_parse.ml";
  cmd "cp ../src/env/omake_ir_ast.ml omake_ir_ast.ml";
  cmd "cp ../src/env/omake_ir_ast.mli omake_ir_ast.mli";
  cmd "cp ../src/env/omake_ir_semant.ml omake_ir_semant.ml";
  cmd "cp ../src/env/omake_ir_semant.mli omake_ir_semant.mli";
  cmd "cp ../src/env/omake_ast_lex.mll omake_ast_lex.mll";
  cmd "cp ../src/env/omake_ast_parse.input omake_ast_parse.input";
  cmd "cp ../src/env/omake_exp_parse.mly omake_exp_parse.mly";
  cmd "cp ../src/shell/omake_shell_completion.ml omake_shell_completion.ml";
  cmd "cp ../src/shell/omake_shell_completion.mli omake_shell_completion.mli";
  cmd "cp ../src/shell/omake_shell_job.ml omake_shell_job.ml";
  cmd "cp ../src/shell/omake_shell_job.mli omake_shell_job.mli";
  cmd "cp ../src/shell/omake_shell_lex.ml omake_shell_lex.ml";
  cmd "cp ../src/shell/omake_shell_lex.mli omake_shell_lex.mli";
  cmd "cp ../src/shell/omake_shell_spawn.ml omake_shell_spawn.ml";
  cmd "cp ../src/shell/omake_shell_spawn.mli omake_shell_spawn.mli";
  cmd "cp ../src/shell/omake_shell_sys.mli omake_shell_sys.mli";
  cmd "cp ../src/shell/omake_shell_sys_type.ml omake_shell_sys_type.ml";
  cmd "cp ../src/shell/omake_shell_parse.mly omake_shell_parse.mly";
  cmd "cp ../src/shell/omake_shell_sys_win32.ml omake_shell_sys.ml";
  cmd "cp ../src/eval/omake_eval.ml omake_eval.ml";
  cmd "cp ../src/eval/omake_eval.mli omake_eval.mli";
  cmd "cp ../src/eval/omake_value.ml omake_value.ml";
  cmd "cp ../src/eval/omake_value.mli omake_value.mli";
  cmd "cp ../src/build/omake_build.ml omake_build.ml";
  cmd "cp ../src/build/omake_build.mli omake_build.mli";
  cmd "cp ../src/build/omake_build_tee.ml omake_build_tee.ml";
  cmd "cp ../src/build/omake_build_tee.mli omake_build_tee.mli";
  cmd "cp ../src/build/omake_build_type.ml omake_build_type.ml";
  cmd "cp ../src/build/omake_build_util.ml omake_build_util.ml";
  cmd "cp ../src/build/omake_build_util.mli omake_build_util.mli";
  cmd "cp ../src/build/omake_builtin.ml omake_builtin.ml";
  cmd "cp ../src/build/omake_builtin.mli omake_builtin.mli";
  cmd "cp ../src/build/omake_builtin_type.ml omake_builtin_type.ml";
  cmd "cp ../src/build/omake_rule.ml omake_rule.ml";
  cmd "cp ../src/build/omake_rule.mli omake_rule.mli";
  cmd "cp ../src/build/omake_target.ml omake_target.ml";
  cmd "cp ../src/build/omake_target.mli omake_target.mli";
  cmd "cp ../src/builtin/omake_builtin_arith.ml omake_builtin_arith.ml";
  cmd "cp ../src/builtin/omake_builtin_arith.mli omake_builtin_arith.mli";
  cmd "cp ../src/builtin/omake_builtin_base.ml omake_builtin_base.ml";
  cmd "cp ../src/builtin/omake_builtin_base.mli omake_builtin_base.mli";
  cmd "cp ../src/builtin/omake_builtin_file.ml omake_builtin_file.ml";
  cmd "cp ../src/builtin/omake_builtin_file.mli omake_builtin_file.mli";
  cmd "cp ../src/builtin/omake_builtin_fun.ml omake_builtin_fun.ml";
  cmd "cp ../src/builtin/omake_builtin_fun.mli omake_builtin_fun.mli";
  cmd "cp ../src/builtin/omake_builtin_io.ml omake_builtin_io.ml";
  cmd "cp ../src/builtin/omake_builtin_io.mli omake_builtin_io.mli";
  cmd "cp ../src/builtin/omake_builtin_io_fun.ml omake_builtin_io_fun.ml";
  cmd "cp ../src/builtin/omake_builtin_io_fun.mli omake_builtin_io_fun.mli";
  cmd "cp ../src/builtin/omake_builtin_object.ml omake_builtin_object.ml";
  cmd "cp ../src/builtin/omake_builtin_object.mli omake_builtin_object.mli";
  cmd "cp ../src/builtin/omake_builtin_ocamldep.ml omake_builtin_ocamldep.ml";
  cmd "cp ../src/builtin/omake_builtin_rule.ml omake_builtin_rule.ml";
  cmd "cp ../src/builtin/omake_builtin_rule.mli omake_builtin_rule.mli";
  cmd "cp ../src/builtin/omake_builtin_shell.ml omake_builtin_shell.ml";
  cmd "cp ../src/builtin/omake_builtin_shell.mli omake_builtin_shell.mli";
  cmd "cp ../src/builtin/omake_builtin_sys.ml omake_builtin_sys.ml";
  cmd "cp ../src/builtin/omake_builtin_sys.mli omake_builtin_sys.mli";
  cmd "cp ../src/builtin/omake_builtin_target.ml omake_builtin_target.ml";
  cmd "cp ../src/builtin/omake_builtin_target.mli omake_builtin_target.mli";
  cmd "cp ../src/builtin/omake_builtin_test.ml omake_builtin_test.ml";
  cmd "cp ../src/builtin/omake_builtin_test.mli omake_builtin_test.mli";
  cmd "cp ../src/builtin/omake_builtin_util.ml omake_builtin_util.ml";
  cmd "cp ../src/builtin/omake_builtin_util.mli omake_builtin_util.mli";
  cmd "cp ../src/builtin/omake_printf.ml omake_printf.ml";
  cmd "cp ../src/builtin/omake_printf.mli omake_printf.mli";
  cmd "cp ../src/main/omake_main.ml omake_main.ml";
  cmd "cp ../src/main/omake_main.mli omake_main.mli";
  cmd "cp ../src/main/omake_main_util.ml omake_main_util.ml";
  cmd "cp ../src/main/omake_shell.ml omake_shell.ml";
  cmd "cp ../src/main/omake_shell.mli omake_shell.mli";
  cmd "cp ../version.txt version.txt";
  cmd "ocamllex.opt omake_ast_lex.mll";
  cmd "ocamlc.opt -w +a-4-32-30-42-40-41 -g  -c omake_gen_parse.ml";
  cmd "ocamlc.opt -w +a-4-32-30-42-40-41 -g  -thread -custom -o omake_gen_parse.byte unix.cma threads.cma  omake_gen_parse.cmo";
  cmx_of_ml "omake_gen_parse.ml";
  cmd (ocamlopt ^ " -o omake_gen_parse.opt.exe  unix.cmxa threads.cmxa  omake_gen_parse.cmx");
  cmd "cp omake_gen_parse.opt.exe omake_gen_parse.exe";
  cmd "omake_gen_parse -o omake_ast_parse.mly omake_ast_parse.input";
  cmd "ocamlyacc omake_ast_parse.mly";
  cmd "ocamlyacc omake_exp_parse.mly";
  cmd "ocamlyacc omake_shell_parse.mly";
  cmi_of_mli "lm_debug.mli";
  cmx_of_ml "lm_debug.ml";
  cmi_of_mli "lm_string_util.mli";
  cmx_of_ml "lm_string_util.ml";
  cmx_of_ml "omake_gen_magic.ml";
  cmi_of_mli "lm_printf.mli";
  cmx_of_ml "lm_printf.ml";
  cmi_of_mli "lm_heap.mli";
  cmx_of_ml "lm_heap.ml";
  cmi_of_mli "lm_list_util.mli";
  cmx_of_ml "lm_list_util.ml";
  cmi_of_mli "lm_array_util.mli";
  cmx_of_ml "lm_array_util.ml";
  cmx_of_ml "lm_set_sig.ml";
  cmi_of_mli "lm_set_sig.ml";
  cmi_of_mli "lm_set.mli";
  cmx_of_ml "lm_set.ml";
  cmx_of_ml "lm_map_sig.ml";
  cmi_of_mli "lm_map_sig.ml";
  cmi_of_mli "lm_map.mli";
  cmx_of_ml "lm_map.ml";
  cmi_of_mli "lm_int_set.mli";
  cmx_of_ml "lm_int_set.ml";
  cmi_of_mli "lm_termsize.mli";
  cmx_of_ml "lm_termsize.ml";
  cmi_of_mli "lm_terminfo.mli";
  cmx_of_ml "lm_terminfo.ml";
  cmi_of_mli "lm_arg.mli";
  cmx_of_ml "lm_arg.ml";
  cmi_of_mli "lm_index.mli";
  cmx_of_ml "lm_index.ml";
  cmx_of_ml "lm_thread_sig.ml";
  cmi_of_mli "lm_thread_sig.ml";
  cmi_of_mli "lm_thread_core.mli";
  cmx_of_ml "lm_thread_core.ml";
  cmi_of_mli "lm_thread.mli";
  cmx_of_ml "lm_thread.ml";
  cmi_of_mli "lm_string_set.mli";
  cmx_of_ml "lm_string_set.ml";
  cmi_of_mli "lm_hash.mli";
  cmx_of_ml "lm_hash.ml";
  cmi_of_mli "lm_hash_code.mli";
  cmx_of_ml "lm_hash_code.ml";
  cmi_of_mli "lm_symbol.mli";
  cmx_of_ml "lm_symbol.ml";
  cmi_of_mli "lm_location.mli";
  cmx_of_ml "lm_location.ml";
  cmi_of_mli "lm_position.mli";
  cmx_of_ml "lm_position.ml";
  cmi_of_mli "lm_filename_util.mli";
  cmx_of_ml "lm_filename_util.ml";
  cmi_of_mli "lm_uname.mli";
  cmx_of_ml "lm_uname.ml";
  cmi_of_mli "lm_thread_pool.mli";
  cmx_of_ml "lm_thread_pool.ml";
  cmi_of_mli "lm_channel.mli";
  cmx_of_ml "lm_channel.ml";
  cmi_of_mli "lm_unix_util.mli";
  cmx_of_ml "lm_unix_util.ml";
  cmi_of_mli "lm_db.mli";
  cmx_of_ml "lm_db.ml";
  cmi_of_mli "lm_notify.mli";
  cmx_of_ml "lm_notify.ml";
  cmi_of_mli "lm_fs_case_sensitive.mli";
  cmx_of_ml "lm_fs_case_sensitive.ml";
  cmi_of_mli "lm_wild.mli";
  cmx_of_ml "lm_wild.ml";
  cmi_of_mli "lm_readline.mli";
  cmx_of_ml "lm_readline.ml";
  cmi_of_mli "lm_marshal.mli";
  cmx_of_ml "lm_marshal.ml";
  cmi_of_mli "lm_handle_table.mli";
  cmx_of_ml "lm_handle_table.ml";
  cmi_of_mli "lm_int_handle_table.mli";
  cmx_of_ml "lm_int_handle_table.ml";
  cmi_of_mli "lm_bitset.mli";
  cmx_of_ml "lm_bitset.ml";
  cmi_of_mli "lm_instrument.mli";
  cmx_of_ml "lm_instrument.ml";
  cmd (ocamlopt ^ " -a -o lm.cmxa lm_printf.cmx lm_debug.cmx lm_heap.cmx lm_list_util.cmx lm_array_util.cmx lm_set_sig.cmx lm_set.cmx lm_map_sig.cmx lm_map.cmx lm_int_set.cmx lm_termsize.cmx lm_terminfo.cmx lm_arg.cmx lm_index.cmx lm_thread_sig.cmx lm_thread_core.cmx lm_thread.cmx lm_string_util.cmx lm_string_set.cmx lm_hash.cmx lm_hash_code.cmx lm_symbol.cmx lm_location.cmx lm_position.cmx lm_filename_util.cmx lm_uname.cmx lm_thread_pool.cmx lm_channel.cmx lm_unix_util.cmx lm_db.cmx lm_notify.cmx lm_fs_case_sensitive.cmx lm_wild.cmx lm_readline.cmx lm_marshal.cmx lm_handle_table.cmx lm_int_handle_table.cmx lm_bitset.cmx lm_instrument.cmx");
  cmi_of_mli "lm_hash_cons.mli";
  cmx_of_ml "lm_hash_cons.ml";
  cmi_of_mli "lm_lexer.mli";
  cmx_of_ml "lm_lexer.ml";
  cmi_of_mli "lm_parser.mli";
  cmx_of_ml "lm_parser.ml";
  cmi_of_mli "lm_glob.mli";
  cmx_of_ml "lm_glob.ml";
  cmd (ocamlopt ^ " -a -o frt.cmxa lm_hash_cons.cmx lm_lexer.cmx lm_parser.cmx lm_glob.cmx");
  co_of_c "c_lm_heap.c";
  co_of_c "c_lm_channel.c";
  co_of_c "c_lm_printf.c";
  co_of_c "c_lm_ctype.c";
  co_of_c "c_lm_uname_ext.c";
  co_of_c "c_lm_unix_cutil.c";
  co_of_c "c_lm_compat_win32.c";
  co_of_c "c_readline.c";
  co_of_c "c_omake_shell_sys.c";
  co_of_c "c_omake_shell_spawn.c";
  co_of_c "c_fam_win32.c";
  co_of_c "c_fam_kqueue.c";
  co_of_c "c_fam_inotify.c";
  co_of_c "c_lm_notify.c";
  co_of_c "c_lm_termsize.c";
  co_of_c "c_lm_terminfo.c";
  co_of_c "c_lm_fs_case_sensitive.c";
  cmd "del clib.a";
  cmd "i686-w64-mingw32-ar cq clib.a c_lm_heap.co c_lm_channel.co c_lm_printf.co c_lm_ctype.co c_lm_uname_ext.co c_lm_unix_cutil.co c_lm_compat_win32.co c_readline.co c_omake_shell_sys.co c_omake_shell_spawn.co c_fam_win32.co c_fam_kqueue.co c_fam_inotify.co c_lm_notify.co c_lm_termsize.co c_lm_terminfo.co c_lm_fs_case_sensitive.co";
  cmd (ocamlopt ^ " -o omake_gen_magic.opt.exe -cclib clib.a unix.cmxa threads.cmxa lm.cmxa frt.cmxa omake_gen_magic.cmx");
  cmd "cp omake_gen_magic.opt.exe omake_gen_magic.exe";
  cmd "omake_gen_magic -o omake_magic.ml --version version.txt --var \"omake_cc=i686-w64-mingw32-gcc\" --var \"omake_cflags=\"  --var \"omake_ccomptype=cc\" --magic --cache-files lm_filename_util.ml lm_hash.ml lm_location.ml lm_map.ml lm_position.ml lm_set.ml lm_symbol.ml omake_value_type.ml omake_cache.ml omake_cache_type.ml omake_node.ml omake_command_digest.ml --omc-files lm_filename_util.ml lm_hash.ml lm_location.ml lm_symbol.ml lm_map.ml lm_set.ml omake_node.ml omake_ir.ml --omo-files lm_filename_util.ml lm_hash.ml lm_lexer.ml lm_location.ml lm_map.ml lm_parser.ml lm_position.ml lm_set.ml lm_symbol.ml omake_value_type.ml omake_cache_type.ml omake_ir.ml omake_node.ml omake_env.ml";
  cmx_of_ml "omake_magic.ml";
  cmd (ocamlopt ^ " -a -o magic.cmxa omake_magic.cmx");
  cmx_of_ml "omake_symbol.ml";
  cmx_of_ml "omake_node_sig.ml";
  cmi_of_mli "omake_magic.ml";
  cmd "ocamlc.opt -w +a-4-32-30-42-40-41 -g -thread  -a -o magic.cma omake_magic.cmo";
  cmi_of_mli "omake_state.mli";
  cmx_of_ml "omake_state.ml";
  cmi_of_mli "omake_node_sig.ml";
  cmi_of_mli "omake_node.mli";
  cmx_of_ml "omake_node.ml";
  cmx_of_ml "omake_ir.ml";
  cmi_of_mli "omake_ir.ml";
  cmi_of_mli "omake_var.mli";
  cmx_of_ml "omake_var.ml";
  cmx_of_ml "omake_lexer.ml";
  cmx_of_ml "omake_parser.ml";
  cmx_of_ml "omake_ir_util.ml";
  cmi_of_mli "omake_ir_util.ml";
  cmi_of_mli "omake_ir_free_vars.mli";
  cmx_of_ml "omake_ir_free_vars.ml";
  cmx_of_ml "omake_ast.ml";
  cmx_of_ml "omake_value_type.ml";
  cmi_of_mli "omake_symbol.ml";
  cmi_of_mli "omake_lexer.ml";
  cmi_of_mli "omake_parser.ml";
  cmi_of_mli "omake_ast.ml";
  cmi_of_mli "omake_value_type.ml";
  cmi_of_mli "omake_value_util.mli";
  cmx_of_ml "omake_value_util.ml";
  cmi_of_mli "omake_ast_util.mli";
  cmx_of_ml "omake_ast_util.ml";
  cmi_of_mli "omake_ast_print.mli";
  cmx_of_ml "omake_ast_print.ml";
  cmi_of_mli "omake_ir_print.mli";
  cmx_of_ml "omake_ir_print.ml";
  cmi_of_mli "omake_command_type.mli";
  cmx_of_ml "omake_command_type.ml";
  cmi_of_mli "omake_value_print.mli";
  cmx_of_ml "omake_value_print.ml";
  cmi_of_mli "omake_pos.mli";
  cmx_of_ml "omake_pos.ml";
  cmx_of_ml "omake_shell_type.ml";
  cmi_of_mli "omake_options.mli";
  cmx_of_ml "omake_options.ml";
  cmi_of_mli "omake_exec_id.mli";
  cmx_of_ml "omake_exec_id.ml";
  cmx_of_ml "omake_exec_type.ml";
  cmi_of_mli "omake_exec_type.ml";
  cmi_of_mli "omake_exec_print.mli";
  cmx_of_ml "omake_exec_print.ml";
  cmi_of_mli "omake_exec_util.mli";
  cmx_of_ml "omake_exec_util.ml";
  cmi_of_mli "omake_exec_local.mli";
  cmx_of_ml "omake_exec_local.ml";
  cmi_of_mli "omake_exec_remote.mli";
  cmx_of_ml "omake_exec_remote.ml";
  cmi_of_mli "omake_exec_notify.mli";
  cmx_of_ml "omake_exec_notify.ml";
  cmi_of_mli "omake_exec.mli";
  cmx_of_ml "omake_exec.ml";
  cmx_of_ml "omake_cache_type.ml";
  cmi_of_mli "omake_cache_type.ml";
  cmi_of_mli "omake_cache.mli";
  cmx_of_ml "omake_cache.ml";
  cmi_of_mli "omake_shell_type.ml";
  cmi_of_mli "omake_env.mli";
  cmx_of_ml "omake_env.ml";
  cmi_of_mli "omake_ir_semant.mli";
  cmx_of_ml "omake_ir_semant.ml";
  cmi_of_mli "omake_ir_ast.mli";
  cmx_of_ml "omake_ir_ast.ml";
  cmi_of_mli "omake_exp_parse.mli";
  cmx_of_ml "omake_exp_parse.ml";
  cmi_of_mli "omake_exp_lex.mli";
  cmx_of_ml "omake_exp_lex.ml";
  cmi_of_mli "omake_command_digest.mli";
  cmx_of_ml "omake_command_digest.ml";
  cmi_of_mli "omake_command.mli";
  cmx_of_ml "omake_command.ml";
  cmi_of_mli "omake_ast_lex.mli";
  cmi_of_mli "omake_exn_print.mli";
  cmx_of_ml "omake_exn_print.ml";
  cmi_of_mli "omake_ast_parse.mli";
  cmx_of_ml "omake_ast_parse.ml";
  cmx_of_ml "omake_ast_lex.ml";
  cmi_of_mli "omake_eval.mli";
  cmx_of_ml "omake_eval.ml";
  cmi_of_mli "omake_value.mli";
  cmx_of_ml "omake_value.ml";
  cmi_of_mli "omake_shell_parse.mli";
  cmx_of_ml "omake_shell_parse.ml";
  cmi_of_mli "omake_shell_lex.mli";
  cmx_of_ml "omake_shell_lex.ml";
  cmx_of_ml "omake_shell_sys_type.ml";
  cmi_of_mli "omake_shell_sys_type.ml";
  cmi_of_mli "omake_shell_sys.mli";
  cmx_of_ml "omake_shell_sys.ml";
  cmi_of_mli "omake_shell_job.mli";
  cmx_of_ml "omake_shell_job.ml";
  cmi_of_mli "omake_rule.mli";
  cmx_of_ml "omake_rule.ml";
  cmx_of_ml "omake_build_type.ml";
  cmx_of_ml "omake_builtin_type.ml";
  cmi_of_mli "omake_build_type.ml";
  cmi_of_mli "omake_build_tee.mli";
  cmx_of_ml "omake_build_tee.ml";
  cmi_of_mli "omake_build_util.mli";
  cmx_of_ml "omake_build_util.ml";
  cmi_of_mli "omake_builtin_type.ml";
  cmi_of_mli "omake_builtin.mli";
  cmx_of_ml "omake_builtin.ml";
  cmx_of_ml "omake_main_util.ml";
  cmi_of_mli "omake_shell_completion.mli";
  cmx_of_ml "omake_shell_completion.ml";
  cmi_of_mli "omake_shell.mli";
  cmx_of_ml "omake_shell.ml";
  cmi_of_mli "omake_install.mli";
  cmx_of_ml "omake_install.ml";
  cmi_of_mli "omake_builtin_util.mli";
  cmx_of_ml "omake_builtin_util.ml";
  cmi_of_mli "omake_builtin_io_fun.mli";
  cmx_of_ml "omake_builtin_io_fun.ml";
  cmi_of_mli "omake_target.mli";
  cmx_of_ml "omake_target.ml";
  cmi_of_mli "omake_build.mli";
  cmx_of_ml "omake_build.ml";
  cmi_of_mli "omake_main.mli";
  cmx_of_ml "omake_main.ml";
  cmd (ocamlopt ^ " -a -o ast.cmxa omake_ast.cmx omake_ast_util.cmx omake_ast_print.cmx");
  cmx_of_ml "omake_node_type.ml";
  cmd (ocamlopt ^ " -a -o ir.cmxa omake_options.cmx omake_symbol.cmx omake_state.cmx omake_node_type.cmx omake_node_sig.cmx omake_node.cmx omake_install.cmx omake_ir.cmx omake_var.cmx omake_ir_util.cmx omake_ir_print.cmx omake_ir_free_vars.cmx omake_lexer.cmx omake_parser.cmx omake_value_type.cmx omake_command_type.cmx omake_value_util.cmx omake_value_print.cmx omake_pos.cmx omake_shell_type.cmx omake_command.cmx omake_cache_type.cmx omake_cache.cmx");
  cmd (ocamlopt ^ " -a -o env.cmxa omake_env.cmx omake_exn_print.cmx omake_ast_parse.cmx omake_ast_lex.cmx omake_exp_parse.cmx omake_exp_lex.cmx omake_ir_ast.cmx omake_ir_semant.cmx omake_command_digest.cmx");
  cmd (ocamlopt ^ " -a -o exec.cmxa omake_exec_id.cmx omake_exec_type.cmx omake_exec_print.cmx omake_exec_util.cmx omake_exec_local.cmx omake_exec_remote.cmx omake_exec_notify.cmx omake_exec.cmx");
  cmd (ocamlopt ^ " -a -o eval.cmxa omake_eval.cmx omake_value.cmx");
  cmi_of_mli "omake_shell_spawn.mli";
  cmx_of_ml "omake_shell_spawn.ml";
  cmd (ocamlopt ^ " -a -o shell.cmxa omake_shell_parse.cmx omake_shell_lex.cmx omake_shell_spawn.cmx omake_shell_sys_type.cmx omake_shell_sys.cmx omake_shell_job.cmx omake_shell_completion.cmx");
  cmd (ocamlopt ^ " -a -o build.cmxa omake_rule.cmx omake_build_type.cmx omake_build_tee.cmx omake_build_util.cmx omake_builtin_type.cmx omake_target.cmx omake_builtin.cmx omake_build.cmx");
  cmi_of_mli "omake_printf.mli";
  cmx_of_ml "omake_printf.ml";
  cmi_of_mli "omake_builtin_base.mli";
  cmx_of_ml "omake_builtin_base.ml";
  cmi_of_mli "omake_builtin_arith.mli";
  cmx_of_ml "omake_builtin_arith.ml";
  cmi_of_mli "omake_builtin_file.mli";
  cmx_of_ml "omake_builtin_file.ml";
  cmi_of_mli "omake_builtin_fun.mli";
  cmx_of_ml "omake_builtin_fun.ml";
  cmi_of_mli "omake_builtin_io.mli";
  cmx_of_ml "omake_builtin_io.ml";
  cmi_of_mli "omake_builtin_sys.mli";
  cmx_of_ml "omake_builtin_sys.ml";
  cmi_of_mli "omake_builtin_target.mli";
  cmx_of_ml "omake_builtin_target.ml";
  cmi_of_mli "omake_builtin_shell.mli";
  cmx_of_ml "omake_builtin_shell.ml";
  cmi_of_mli "omake_builtin_rule.mli";
  cmx_of_ml "omake_builtin_rule.ml";
  cmi_of_mli "omake_builtin_object.mli";
  cmx_of_ml "omake_builtin_object.ml";
  cmi_of_mli "omake_builtin_test.mli";
  cmx_of_ml "omake_builtin_test.ml";
  cmx_of_ml "omake_builtin_ocamldep.ml";
  cmd (ocamlopt ^ " -linkall -a -o builtin.cmxa omake_printf.cmx omake_builtin_util.cmx omake_builtin_base.cmx omake_builtin_arith.cmx omake_builtin_file.cmx omake_builtin_fun.cmx omake_builtin_io.cmx omake_builtin_io_fun.cmx omake_builtin_sys.cmx omake_builtin_target.cmx omake_builtin_shell.cmx omake_builtin_rule.cmx omake_builtin_object.cmx omake_builtin_test.cmx omake_builtin_ocamldep.cmx");
  cmd (ocamlopt ^ " -o omake.opt.exe -cclib clib.a unix.cmxa threads.cmxa lm.cmxa frt.cmxa magic.cmxa ast.cmxa ir.cmxa env.cmxa exec.cmxa eval.cmxa shell.cmxa build.cmxa builtin.cmxa omake_main_util.cmx omake_shell.cmx omake_main.cmx");
  cmd "cp omake.opt.exe omake.exe";
  cmd "cp omake.exe ../omake-boot.exe";
  print_endline "done"
