#
# Bootstrap program is omake-boot.exe
#
default:
	@echo "If you have already built omake, you should use it instead of make."
	@echo "If you need to bootstrap, use "
	@echo " - 'nmake -f Makefile.nt bootstrap',"
	@echo "       to build the bootstrapping (feature-limited) OMake binary 'omake-boot.exe'."
	@echo " - 'nmake -f Makefile.nt all',"
	@echo "       to bootstrap and then build everything."
	@echo " - 'nmake -f Makefile.nt install',"
	@echo "       to bootstrap, build, and install everything."
	@exit 1

NMAKE = $(MAKE) /nologo -f Makefile.nt

bootstrap: boot\Makefile.nt boot\Makefile.dep
	cd boot
	$(NMAKE) Makefile.dep
	$(NMAKE) omake.exe
	copy omake.exe ..\omake-boot.exe
	cd ..

.config:
	echo # Empty config > .config

all: bootstrap .config
	set OMAKEFLAGS=
	set OMAKEPATH=lib
	.\omake-boot --dotomake .omake --force-dotomake -j2 main src\main\osh.exe
	src\main\omake --dotomake .omake --force-dotomake -j2 all

install: all
	set OMAKEFLAGS=
	set OMAKEPATH=lib
	.\omake-boot --dotomake .omake --force-dotomake -j2 install

aip-install: all
	mkdir ..\omake-install
	set OMAKEFLAGS=
	set OMAKEPATH=lib
	set BINDIR=../omake-install/bin
	set LIBDIR=../omake-install/lib
	.\omake-boot --dotomake .omake --force-dotomake -j2 install

boot\Makefile.nt: src\Makefile.nt
	-mkdir boot
	copy src\Makefile.nt boot\Makefile.nt

boot\Makefile.dep:
	echo # Dependencies > $@
